### ISSUE TITLE
Add lectures & assignments to course

### ISSUE THREAD

**Issue by fravl** [samuelashraff/rest-to-graphql-migration#22]
Whole flow (front + back)

Lectures
- can be added
- can be deleted

Assignments 
- can be added
- can be deleted
- can be marked complete

**Datamodels** (see Study Tracker App google docs)
Lectures:
- Date: date
- Starttime: time
- Endtime: time
- Location: string
- Obligatory: boolean

Assignments
- Type: ‘exam’ | ‘report’  (enum) 
- Group: boolean
- Deadline: date
- Obligatory: boolean

**Comment by Nurou** [comment]
Perhaps Type: ‘exam’ | ‘report’ (enum) -> Description: string
