### ISSUE TITLE
View upcoming lectures and deadlines

### ISSUE THREAD

**Issue by fravl** [samuelashraff/rest-to-graphql-migration#23]
Viewable as a list next to the course grid (see https://excalidraw.com/#room=5e8d05405338927c9987,MJ6ZnwovtIEwzZ38siDiiQ)

**Comment by Nurou** [comment]
<img width="1169" alt="CleanShot 2023-10-31 at 16 50 55@2x" src="https://github.com/samuelashraff/rest-to-graphql-migration/assets/23085643/60a3de86-3f9a-417c-8dd5-75610deae4e9">
